packages:
  # main apps & packages
  - "apps/*"
  - "packages/*"
  # air tooling apps & packages
  - "air/apps/*"
  - "air/packages/*"
  # flash apps, libraries & packages
  - "flash/apps/*"
  - "flash/packages/*"
